server:
  port: 8401


spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址
        server-addr: 47.95.211.172:8848
    sentinel:
      transport:
#        #配置Sentinel dashboard地址，docker对应的为 8858
#        dashboard: 47.95.211.172:8858
#        #配置本地 ip 地址，使用 docker 安装添加配置
#        client-ip: 192.168.0.7
        #配置Sentinel dashboard地址，本地默认对应的为 8080
        dashboard: localhost:8081
        #配置Sentinel后台监控端口，默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719




management:
  endpoints:
    web:
      exposure:
        include: '*'